---
# handlers file for DatabaseSetup

  - name: Restart MariaDB
    service:
      name: mariadb
      state: restarted
    become: true

  - name: Restart PostgreSQL
    service:
      name: postgresql
      state: restarted
    become: true