---
# tasks file for UpdateSystem

### UPDATE SYSTEM

  - name: Update system
    apt:
      update_cache: yes
      upgrade: yes
    become: true

  - name: Set timezone Brussels
    timezone:
      name: Europe/Brussels
    become: true